### ISSUE TITLE
Add more rules

### ISSUE THREAD

**Issue by filipalacerda** [mysticatea/eslint-plugin-vue-trial#2]
Hi! I've opened an issue on eslint-plugin-vue and was pointed to this repo!

What do you think of the following rules? https://github.com/vuejs/eslint-plugin-vue/issues/10 

I can submit a PR with them, but wanted to check first 😊

**Comment by mysticatea** [comment]
Thank you for this issue.

Sure, I'm interested in making more rules.
However, I have been encountered some problems of [the parser], so I will solve those. 

- https://github.com/mysticatea/eslint-plugin-vue-trial/blob/master/docs/rules/html-end-tags.md#todo-brbr
- https://github.com/mysticatea/eslint-plugin-vue-trial/blob/master/docs/rules/no-duplicate-attributes.md#todo-div-foo-foodiv

After l solve the problems, I will send [the parser] and the rules of this repo to the official plugin. Then, I want to make more rules in the official plugin.

I was not sure whether this challenge can get success or not because it's my first experience that I use parserServices feature of ESLint, so I made this repo to try it. So, this repo's name is trial :D 

[the parser]: https://github.com/mysticatea/vue-eslint-parser

**Comment by filipalacerda** [comment]
Thank you @mysticatea!
I didn't realise what the goal of this repo was 🙊 
In that case I'll move the discussion back to the official one! I'll close this issue for now :)
